import { useState } from "react";
import confetti from "canvas-confetti";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { generateQuiz } from "../api/api";
import { useVoiceInput } from "../hooks/useVoiceInput";
import QuizCard from "../components/QuizCard";
import QuizResult from "../components/QuizResult";
import { HelpCircle, Sparkles, Mic, MicOff, CheckCircle, ArrowRight, ArrowLeft } from "lucide-react";

function Quiz() {
  const [difficulty, setDifficulty] = useState("medium");
  const [count, setCount] = useState(10);
  const [topic, setTopic] = useState("");

  const [questions, setQuestions] = useState([]);
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState({});
  const [loading, setLoading] = useState(false);
  const [finished, setFinished] = useState(false);

  const { isListening, toggleListening } = useVoiceInput((transcript) => {
    setTopic(transcript);
  });

  const loadQuiz = async () => {
    if (!topic.trim()) {
      alert("Please enter or dictate a topic first.");
      return;
    }

    setLoading(true);
    try {
      const data = await generateQuiz(difficulty, count, topic);
      setQuestions(data.questions || []);
      setCurrent(0);
      setAnswers({});
      setFinished(false);
    } catch (err) {
      console.error(err);
      alert("Quiz generation failed. Make sure documents are uploaded.");
    } finally {
      setLoading(false);
    }
  };

  const selectAnswer = (option) => {
    setAnswers({ ...answers, [current]: option });
  };

  const next = () => {
    if (current === questions.length - 1) {
      setFinished(true);
      confetti({ particleCount: 120, spread: 70, origin: { y: 0.6 } });
    } else {
      setCurrent(current + 1);
    }
  };

  const previous = () => {
    if (current > 0) setCurrent(current - 1);
  };

  return (
    <div className="flex h-screen bg-slate-950 text-slate-100 overflow-hidden">
      <Sidebar activePage="quiz" />

      <div className="flex-1 flex flex-col overflow-hidden">
        <Header />

        <main className="flex-1 overflow-y-auto p-6 md:p-8 space-y-6 custom-scrollbar max-w-5xl mx-auto w-full">
          
          {finished ? (
            <QuizResult questions={questions} answers={answers} retry={loadQuiz} />
          ) : (
            <>
              {/* Header */}
              <div className="space-y-2 text-center pt-2">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs font-semibold">
                  <HelpCircle className="w-3.5 h-3.5" /> Topic Quiz Generator
                </div>
                <h1 className="text-3xl font-black text-white tracking-tight">AI Multiple Choice Quiz</h1>
                <p className="text-xs text-slate-400 max-w-md mx-auto">
                  Test your document comprehension with target topic questions generated by Groq LLM.
                </p>
              </div>

              {/* Controls Form */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 shadow-2xl backdrop-blur-xl space-y-4">
                
                <div>
                  <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">
                    Target Topic & Concepts
                  </label>

                  <div className="flex items-center gap-2 bg-slate-950/80 border border-slate-800 rounded-2xl px-4 py-2.5">
                    <input
                      value={topic}
                      onChange={(e) => setTopic(e.target.value)}
                      placeholder={isListening ? "Listening..." : "e.g. Deadlock, Paging, Virtual Memory..."}
                      className="bg-transparent text-sm text-white outline-none flex-1 placeholder:text-slate-500"
                    />

                    <button
                      onClick={toggleListening}
                      title={isListening ? "Listening..." : "Voice Dictate"}
                      className={`p-2 rounded-xl border transition ${
                        isListening
                          ? "bg-rose-500 text-white border-rose-400 animate-pulse"
                          : "bg-slate-800 text-slate-400 hover:text-white border-slate-700"
                      }`}
                    >
                      {isListening ? <MicOff className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                <div className="flex flex-wrap gap-4 items-end justify-between pt-2">
                  <div className="flex gap-4">
                    <div>
                      <label className="block text-xs font-bold text-slate-400 mb-1">Difficulty</label>
                      <select
                        value={difficulty}
                        onChange={(e) => setDifficulty(e.target.value)}
                        className="bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-xs text-white outline-none"
                      >
                        <option value="easy">Easy</option>
                        <option value="medium">Medium</option>
                        <option value="hard">Hard</option>
                      </select>
                    </div>

                    <div>
                      <label className="block text-xs font-bold text-slate-400 mb-1">Questions</label>
                      <select
                        value={count}
                        onChange={(e) => setCount(Number(e.target.value))}
                        className="bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 text-xs text-white outline-none"
                      >
                        <option value={5}>5 Questions</option>
                        <option value={10}>10 Questions</option>
                        <option value={20}>20 Questions</option>
                      </select>
                    </div>
                  </div>

                  <button
                    onClick={loadQuiz}
                    disabled={loading}
                    className="px-6 py-3 rounded-2xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs transition shadow-lg shadow-emerald-500/20 disabled:opacity-40 flex items-center gap-2 shrink-0"
                  >
                    {loading ? (
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        <span>Generate Quiz</span>
                      </>
                    )}
                  </button>
                </div>

              </div>

              {/* Active Quiz Question */}
              {questions.length > 0 && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between text-xs text-slate-400 px-1">
                    <span>Question {current + 1} of {questions.length}</span>
                    <span className="capitalize text-emerald-400 font-semibold">{difficulty} • {topic}</span>
                  </div>

                  <div className="w-full bg-slate-900 rounded-full h-2 overflow-hidden border border-slate-800">
                    <div
                      className="bg-emerald-500 h-full transition-all duration-300"
                      style={{ width: `${((current + 1) / questions.length) * 100}%` }}
                    />
                  </div>

                  <QuizCard
                    question={questions[current]}
                    selected={answers[current]}
                    onSelect={selectAnswer}
                  />

                  <div className="flex justify-between pt-4">
                    <button
                      onClick={previous}
                      disabled={current === 0}
                      className="px-5 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-750 text-slate-300 text-xs font-semibold transition disabled:opacity-30 flex items-center gap-1.5"
                    >
                      <ArrowLeft className="w-4 h-4" /> Previous
                    </button>

                    <button
                      onClick={next}
                      className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold transition shadow-lg shadow-emerald-500/20 flex items-center gap-1.5"
                    >
                      <span>{current === questions.length - 1 ? "Finish Quiz" : "Next Question"}</span>
                      {current === questions.length - 1 ? <CheckCircle className="w-4 h-4" /> : <ArrowRight className="w-4 h-4" />}
                    </button>
                  </div>
                </div>
              )}

            </>
          )}

        </main>
      </div>
    </div>
  );
}

export default Quiz;
